# Generated by Django 6.0.4 on 2026-05-22 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему письма', max_length=100, verbose_name='Тема письма')),
                ('content', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите Email', max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите Имя, Фамилию и Отчество', max_length=100, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(help_text='Введите комментарий', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылок',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Введите дату и время начало рассылки', verbose_name='Начало рассылки')),
                ('end_time', models.DateTimeField(help_text='Введите дату и время окончания рассылки', verbose_name='Конец рассылки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, verbose_name='Статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сообщение', to='mailing_service.message')),
                ('recipients', models.ManyToManyField(related_name='Сообщения', to='mailing_service.recipient')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
