# Generated by Django 6.0.4 on 2026-05-26 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_mailing_created_at_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='Сообщение',
                to='mailing_service.message',
                verbose_name='Сообщение',
            ),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(
                related_name='Сообщения', to='mailing_service.recipient', verbose_name='Получатели рассылки'
            ),
        ),
    ]
