# Generated by Django 6.0.4 on 2026-05-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0004_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mailings',
                to='mailing_service.message',
                verbose_name='Сообщение',
            ),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(
                blank=True, related_name='mailings', to='mailing_service.recipient', verbose_name='Получатели рассылки'
            ),
        ),
    ]
