# Generated by Django 6.0.4 on 2026-05-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0006_alter_mailing_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='mailings', to='mailing_service.recipient', verbose_name='Получатели рассылки'),
        ),
    ]
