# Generated by Django 6.0.4 on 2026-05-30 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0008_alter_mailing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'attempt_time',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки рассылки'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('success', 'Успешно'), ('failure', 'Не успешно')],
                        max_length=10,
                        verbose_name='Статус попытки',
                    ),
                ),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                (
                    'mailing',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attempts',
                        to='mailing_service.mailing',
                        verbose_name='Рассылка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['-attempt_time'],
            },
        ),
    ]
