# Generated by Django 6.0.4 on 2026-05-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0010_mailing_owner_message_owner_recipient_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={
                'permissions': [('can_disable_distribution', 'Can disable distribution service')],
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
