# Generated by Django 6.0.5 on 2026-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0011_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID запуска рассылки'),
        ),
    ]
